//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// IDeserializable is an interface for wrapping generic objects that might
    /// be returned as part of HTTP requests.
    /// </summary>
    [JsonConverter(typeof(JsonObjectConverter))]
    public interface IDeserializable
    {
        /// <summary>
        /// Returns the internal object as a string.
        /// </summary>
        /// <returns>The internal object as a string.</returns>
        string GetAsString();

        /// <summary>
        /// Gets this object as the given type.
        /// </summary>
        /// <typeparam name="T">The type you want to convert this object to.</typeparam>
        /// <param name="missingMemberHandling">How to handle missing members when deserializing.</param>
        /// <returns>This object as the given type.</returns>
        T GetAs<T>(MissingMemberHandling missingMemberHandling = MissingMemberHandling.Error);
    }

}
