//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Unity.Cloud.Common;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// Base class for constructing requests.
    /// </summary>
    abstract class ApiRequest
    {
        protected string m_PathAndQueryParams;

        /// <summary>
        /// Method function for constructing URL from request base path and query params.
        /// </summary>
        /// <param name="requestBasePath">The start path of a request. </param>
        /// <returns>The full request url. </returns>
        public virtual string ConstructUrl(string requestBasePath)
        {
            return requestBasePath + m_PathAndQueryParams;
        }

        /// <summary>
        /// Method for constructing the request body.
        /// </summary>
        /// <returns>The <see cref="HttpContent"/> representing the request body.</returns>
        public virtual HttpContent ConstructBody()
        {
            return new StringContent("", Encoding.UTF8, "application/json");
        }

        /// <summary>
        /// Helper function to add a provided key and value to the provided
        /// query params and to escape the values correctly if it is a URL.
        /// </summary>
        /// <param name="queryParams">A `List/<string/>` of the query parameters.</param>
        /// <param name="key">The key to be added.</param>
        /// <param name="value">The value to be added.</param>
        /// <returns>Returns a `List/<string/>` with the `key` and `value` added to the provided `queryParams`.</returns>
        protected List<string> AddParamsToQueryParams(List<string> queryParams, string key, string value)
        {
            queryParams.Add($"{key}={value}");
            return queryParams;
        }

        /// <summary>
        /// Helper function to add a provided key and list of values to the
        /// provided query params and to escape the values correctly if it is a
        /// URL.
        /// </summary>
        /// <param name="queryParams">A `List/<string/>` of the query parameters.</param>
        /// <param name="key">The key to be added.</param>
        /// <param name="values">List of values to be added.</param>
        /// <param name="style">string for defining the style, currently unused.</param>
        /// <param name="explode">True if query params should be escaped and added separately.</param>
        /// <returns>Returns a `List/<string/>`</returns>
        protected List<string> AddParamsToQueryParams(List<string> queryParams, string key, List<string> values, string style, bool explode)
        {
            if (explode)
            {
                foreach (var value in values)
                {
                    queryParams.Add($"{key}={value}");
                }
            }
            else
            {
                string paramString = $"{key}=";
                foreach (var value in values)
                {
                    paramString += value + ",";
                }

                paramString = paramString.Remove(paramString.Length - 1);
                queryParams.Add(paramString);
            }

            return queryParams;
        }

        /// <summary>
        /// Helper function to add a provided map of keys and values, representing a model, to the
        /// provided query params.
        /// </summary>
        /// <param name="queryParams">A `List/<string/>` of the query parameters.</param>
        /// <param name="modelVars">A `Dictionary` representing the vars of the model</param>
        /// <returns>Returns a `List/<string/>`</returns>
        protected List<string> AddParamsToQueryParams(List<string> queryParams, Dictionary<string, string> modelVars)
        {
            foreach (var key in modelVars.Keys)
            {
                string escapedValue = modelVars[key];
                queryParams.Add($"{key}={escapedValue}");
            }

            return queryParams;
        }

        /// <summary>
        /// Helper function to add a provided key and value to the provided
        /// query params and to escape the values correctly if it is a URL.
        /// </summary>
        /// <param name="queryParams">A `List/<string/>` of the query parameters.</param>
        /// <param name="key">The key to be added.</param>
        /// <typeparam name="T">The type of the value to be added.</typeparam>
        /// <param name="value">The value to be added.</param>
        /// <returns>Returns a `List/<string/>`</returns>
        protected List<string> AddParamsToQueryParams<T>(List<string> queryParams, string key, T value)
        {
            if (queryParams == null)
            {
                queryParams = new List<string>();
            }

            string valueString = value.ToString();
            queryParams.Add($"{key}={valueString}");
            return queryParams;
        }

        /// <summary>
        /// Constructs a string representing an array path parameter.
        /// </summary>
        /// <param name="pathParam">The list of values to convert to string.</param>
        /// <returns>String representing the param.</returns>
        protected string GetPathParamString(List<string> pathParam)
        {
            string paramString = "";
            foreach (var value in pathParam)
            {
                paramString += value + ",";
            }

            paramString = paramString.Remove(paramString.Length - 1);
            return paramString;
        }
    }
}
