//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// Base class for constructing requests.
    /// </summary>
    abstract class ApiRequest
    {
        protected string m_PathAndQueryParams;
        readonly List<string> m_QueryParams = new List<string>();

        /// <summary>
        /// Method for constructing URL from request base path and query params.
        /// </summary>
        /// <param name="requestBasePath">The start path of a request. </param>
        /// <returns>The full request url. </returns>
        public virtual string ConstructUrl(string requestBasePath)
        {
            var url = requestBasePath + m_PathAndQueryParams;
            if (m_QueryParams.Count > 0)
            {
                url += $"?{string.Join("&", m_QueryParams)}";
            }
            return url;
        }

        /// <summary>
        /// Method for constructing the request headers.
        /// </summary>
        /// <returns>A dictionary containing the request headers.</returns>
        public virtual IEnumerable<(string, string)> GetHeaders()
        {
            yield break;
        }

        /// <summary>
        /// Method for constructing the request body.
        /// </summary>
        /// <returns>The <see cref="HttpContent"/> representing the request body.</returns>
        public virtual HttpContent ConstructBody()
        {
            return new StringContent("", Encoding.UTF8, "application/json");
        }

        /// <summary>
        /// Helper function to add a provided key and value to the provided
        /// query params and to escape the values correctly if it is a URL.
        /// </summary>
        /// <param name="key">The key to be added.</param>
        /// <param name="value">The value to be added.</param>
        protected void AddParamToQueryParams(string key, string value)
        {
            if (string.IsNullOrEmpty(value)) return;

            m_QueryParams.Add($"{key}={value}");
        }

        /// <summary>
        /// Constructs a string representing an array path parameter and adds it to the query params.
        /// </summary>
        /// /// &lt;param name="key"&gt;The key to be added.&lt;/param&gt;
        /// <param name="pathParam">The list of values to convert to string.</param>
        protected void AddParamToQueryParams(string key, IEnumerable<string> pathParam)
        {
            string paramString = "";
            foreach (var value in pathParam)
            {
                paramString += value + ",";
            }

            paramString = paramString.Remove(paramString.Length - 1);

            if (string.IsNullOrEmpty(paramString)) return;

            m_QueryParams.Add($"{key}={paramString}");
        }

        internal bool CheckPathAndQueryContent(params object[] contents)
        {
            foreach (var value in contents.Select(x => x.ToString()))
            {
                if (!m_PathAndQueryParams.Contains(value))
                {
                    if (!IsQueryParam(value)) return false;
                }
            }

            return true;
        }

        bool IsQueryParam(string value)
        {
            for (var i = 0; i < m_QueryParams.Count; ++i)
            {
                if (!value.Contains(m_QueryParams[i])) return false;
            }

            return true;
        }
    }
}
