//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Unity.Cloud.Common;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// GetAssetByIdAndVersionRequest
    /// Get a single asset by id and version.
    /// </summary>
    internal class GetAssetByIdAndVersionRequest : AssetRequest
    {
        /// <summary>Accessor for assetId </summary>
        public string AssetId { get; }

        /// <summary>Accessor for assetVersion </summary>
        public int AssetVersion { get; }

        /// <summary>Accessor for includeFieldsCsv </summary>
        public string IncludeFieldsCsv { get; }

        /// <summary>Accessor for excludeFieldsCsv </summary>
        public string ExcludeFieldsCsv { get; }

        /// <summary>Accessor for includeThumbnailDownloadURLs </summary>
        public bool? IncludeThumbnailDownloadURLs { get; }

        /// <summary>
        /// GetAssetByIdAndVersion Request Object.
        /// Get a single asset by id and version.
        /// </summary>
        /// <param name="organizationId">Genesis ID of the organization</param>
        /// <param name="projectId">ID of the project</param>
        /// <param name="assetId">ID of the asset</param>
        /// <param name="assetVersion">Version of the asset</param>
        /// <param name="includeFieldsCsv">Gets or sets fields to be included in the response, the fields should use csv standard eg. AssetId,Base.Description.</param>
        /// <param name="excludeFieldsCsv">Gets or sets fields to be excluded in the response, the fields should use csv standard eg. AssetId,Base.Description.</param>
        /// <param name="includeThumbnailDownloadURLs">A flag indicating whether the response should have download URL's on files that are marked as thumbnails.</param>
        /// <param name="xCorrelationId">Correlation id of the request.</param>
        public GetAssetByIdAndVersionRequest(ulong organizationId,
            string projectId,
            string assetId,
            int assetVersion,
            string includeFieldsCsv = default(string),
            string excludeFieldsCsv = default(string),
            bool? includeThumbnailDownloadURLs = default(bool?),
            string xCorrelationId = default(string))
            : base(organizationId, projectId, xCorrelationId)
        {
            AssetId = assetId;
            AssetVersion = assetVersion;

            m_PathAndQueryParams += $"/assets/{AssetId}/versions/{AssetVersion}";

            IncludeFieldsCsv = includeFieldsCsv;
            ExcludeFieldsCsv = excludeFieldsCsv;
            IncludeThumbnailDownloadURLs = includeThumbnailDownloadURLs;

            List<string> queryParams = new List<string>();

            if (!string.IsNullOrEmpty(IncludeFieldsCsv))
            {
                queryParams = AddParamsToQueryParams(queryParams, "IncludeFieldsCsv", IncludeFieldsCsv);
            }

            if (!string.IsNullOrEmpty(ExcludeFieldsCsv))
            {
                queryParams = AddParamsToQueryParams(queryParams, "ExcludeFieldsCsv", ExcludeFieldsCsv);
            }

            if (IncludeThumbnailDownloadURLs.HasValue)
            {
                var includeThumbnailDownloadURLsStringValue = IncludeThumbnailDownloadURLs.ToString();
                queryParams = AddParamsToQueryParams(queryParams, "IncludeThumbnailDownloadURLs", includeThumbnailDownloadURLsStringValue);
            }

            if (queryParams.Count > 0)
            {
                m_PathAndQueryParams = $"{m_PathAndQueryParams}?{string.Join("&", queryParams)}";
            }
        }
    }
}
