//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Unity.Cloud.Common;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// GetAssetByIdAndVersionRequest
    /// Get a single asset by id and version.
    /// </summary>
    internal class GetAssetByIdAndVersionRequest : AssetRequest
    {
        /// <summary>
        /// GetAssetByIdAndVersion Request Object.
        /// Get a single asset by id and version.
        /// </summary>
        /// <param name="projectId">ID of the project</param>
        /// <param name="assetId">ID of the asset</param>
        /// <param name="assetVersion">Version of the asset</param>
        /// <param name="includedFieldsFilter">Sets the fields to be included in the response.</param>
        /// <param name="xCorrelationId">Correlation id of the request.</param>
        public GetAssetByIdAndVersionRequest(ProjectId projectId,
            AssetId assetId,
            AssetVersion assetVersion,
            FieldsFilter includedFieldsFilter,
            string xCorrelationId = default(string))
            : base(projectId, assetId, assetVersion, xCorrelationId)
        {
            includedFieldsFilter?.Parse(AddFieldFilterToQueryParams);
        }

        void AddFieldFilterToQueryParams(string value)
        {
            AddParamToQueryParams("IncludeFields", value);
        }
    }
}
