//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System.Collections.Generic;
using System.Net.Mime;

namespace Unity.Cloud.Assets
{
    class GetProjectsByOrganizationAndUserIdsRequest : UsersRequest
    {
        /// <summary>Accessor for userId </summary>
        public string UserId { get; }

        /// <summary>
        /// ApiAssetsUsersV1UserIdOrganizationOrganizationIdProjectsGet Request Object.
        /// Reads a list of projects in an org that a user has access to.
        /// </summary>
        /// <param name="userId">ID of the user</param>
        /// <param name="organizationId">Genesis ID of the organization</param>
        /// <param name="page">The page.</param>
        /// <param name="pageSize">The page size.</param>
        /// <param name="enrichWithUsersCount">A flag indicating whether the projects should have user count.</param>
        /// <param name="xCorrelationId">Correlation id of the request.</param>
        public GetProjectsByOrganizationAndUserIdsRequest(ulong organizationId,
            string userId = null,
            int? page = default(int?),
            int? pageSize = default(int?),
            bool? enrichWithUsersCount = false,
            string xCorrelationId = default(string))
            : base(organizationId, page, pageSize, enrichWithUsersCount, xCorrelationId)
        {
            UserId = string.IsNullOrEmpty(userId) ? "me" : userId;

            m_PathAndQueryParams = $"/users/{UserId}/organizations/{OrganizationId}/projects";

            List<string> queryParams = new List<string>();

            var pageStringValue = Page.ToString();
            queryParams = AddParamsToQueryParams(queryParams, "Page", pageStringValue);
            var pageSizeStringValue = PageSize.ToString();
            queryParams = AddParamsToQueryParams(queryParams, "PageSize", pageSizeStringValue);
            var enrichWithUsersCountStringValue = EnrichWithUsersCount.ToString();
            queryParams = AddParamsToQueryParams(queryParams, "enrichWithUsersCount", enrichWithUsersCountStringValue);

            if (queryParams.Count > 0)
            {
                m_PathAndQueryParams = $"{m_PathAndQueryParams}?{string.Join("&", queryParams)}";
            }
        }
    }
}
