//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System.Collections.Generic;
using System.Net.Mime;
using Unity.Cloud.Common;

namespace Unity.Cloud.Assets
{
    class GetProjectsByOrganizationAndUserIdsRequest : ApiRequest
    {
        /// <summary>
        /// ApiAssetsUsersV1UserIdOrganizationOrganizationIdProjectsGet Request Object.
        /// Reads a list of projects in an org that a user has access to.
        /// </summary>
        /// <param name="userId">ID of the user</param>
        /// <param name="organizationId">Genesis ID of the organization</param>
        /// <param name="page">The page.</param>
        /// <param name="pageSize">The page size.</param>
        /// <param name="enrichWithUsersCount">A flag indicating whether the projects should have user count.</param>
        /// <param name="xCorrelationId">Correlation id of the request.</param>
        public GetProjectsByOrganizationAndUserIdsRequest(OrganizationId organizationId,
            string userId = null,
            int? page = default(int?),
            int? pageSize = default(int?),
            bool? enrichWithUsersCount = false,
            string xCorrelationId = default(string))
        {
            userId = string.IsNullOrEmpty(userId) ? "me" : userId;

            m_PathAndQueryParams = $"/users/{userId}/organizations/{organizationId}/projects";

            AddParamToQueryParams("Page", page.ToString());
            AddParamToQueryParams("Limit", pageSize.ToString());
            AddParamToQueryParams("enrichWithUsersCount", enrichWithUsersCount.ToString());
        }
    }
}
