//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// The asset read filter.
    /// </summary>
    [DataContract(Name = "search_request_filter")]
    internal class SearchRequestFilter
    {
        /// <summary>
        /// The asset read filter.
        /// </summary>
        /// <param name="includeQuery">The dictionary to include all the entries matching all the criteria.</param>
        /// <param name="excludeQuery">The dictionary to exclude all the entries matching all the criteria.</param>
        /// <param name="anyQuery">The dictionary to Include all entries matching any of the criterias.</param>
        /// <param name="anyQueryMinimumMatch">The minimum any query match amount to be considered a match for return.</param>
        /// <param name="collections">The collection paths.</param>
        public SearchRequestFilter(Dictionary<string, object> includeQuery = default, Dictionary<string, object> excludeQuery = default, Dictionary<string, object> anyQuery = default, int? anyQueryMinimumMatch = default, List<string> collections = default)
        {
            IncludeQuery = (Dictionary<string, IDeserializable>) JsonObject.GetNewJsonObjectResponse(includeQuery);
            ExcludeQuery = (Dictionary<string, IDeserializable>) JsonObject.GetNewJsonObjectResponse(excludeQuery);
            AnyQuery = (Dictionary<string, IDeserializable>) JsonObject.GetNewJsonObjectResponse(anyQuery);
            AnyQueryMinimumMatch = anyQueryMinimumMatch;
            Collections = collections;
        }

        /// <summary>
        /// The dictionary to include all the entries matching all the criteria.
        /// </summary>
        [JsonConverter(typeof(JsonObjectCollectionConverter))]
        [DataMember(Name = "includeQuery", EmitDefaultValue = false)]
        public Dictionary<string, IDeserializable> IncludeQuery{ get; }

        /// <summary>
        /// The dictionary to exclude all the entries matching all the criteria.
        /// </summary>
        [JsonConverter(typeof(JsonObjectCollectionConverter))]
        [DataMember(Name = "excludeQuery", EmitDefaultValue = false)]
        public Dictionary<string, IDeserializable> ExcludeQuery{ get; }

        /// <summary>
        /// The dictionary to Include all entries matching any of the criterias.
        /// </summary>
        [JsonConverter(typeof(JsonObjectCollectionConverter))]
        [DataMember(Name = "anyQuery", EmitDefaultValue = false)]
        public Dictionary<string, IDeserializable> AnyQuery{ get; }

        /// <summary>
        /// The minimum any query match amount to be considered a match for return.
        /// </summary>
        [DataMember(Name = "anyQueryMinimumMatch", EmitDefaultValue = false)]
        public int? AnyQueryMinimumMatch{ get; }

        /// <summary>
        /// The collection paths.
        /// </summary>
        [DataMember(Name = "collections", EmitDefaultValue = false)]
        public List<string> Collections{ get; }
    }
}
