//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// Define which fields include or exclude from the reuqest beside the default fields.
    /// </summary>
    [DataContract(Name = "search_request_resultFields")]
    internal class SearchRequestResultFields
    {
        /// <summary>
        /// Define which fields include or exclude from the reuqest beside the default fields.
        /// </summary>
        /// <param name="includeFields">The fields to be returned.</param>
        /// <param name="excludeFields">The fields not to be returned.</param>
        public SearchRequestResultFields(List<string> includeFields = default, List<string> excludeFields = default)
        {
            IncludeFields = includeFields;
            ExcludeFields = excludeFields;
        }

        /// <summary>
        /// The fields to be returned.
        /// </summary>
        [DataMember(Name = "includeFields", EmitDefaultValue = false)]
        public List<string> IncludeFields{ get; }

        /// <summary>
        /// The fields not to be returned.
        /// </summary>
        [DataMember(Name = "excludeFields", EmitDefaultValue = false)]
        public List<string> ExcludeFields{ get; }
    }
}
