//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// The pagination of the request.
    /// </summary>
    [DataContract(Name = "search_request_pagination")]
    internal class SearchRequestPagination
    {
        /// <summary>
        /// The pagination of the request.
        /// </summary>
        /// <param name="sortingField">The field to sort the assets from the page.</param>
        /// <param name="token">The pagination token.</param>
        /// <param name="pageSize">The amount of assets per page.</param>
        public SearchRequestPagination(string sortingField, string token = default, int pageSize = default)
        {
            Token = token;
            PageSize = pageSize;
            SortingField = sortingField;
        }

        /// <summary>
        /// The pagination token.
        /// </summary>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public string Token{ get; }

        /// <summary>
        /// The amount of assets per page.
        /// </summary>
        [DataMember(Name = "pageSize", EmitDefaultValue = false)]
        public int PageSize{ get; }

        /// <summary>
        /// The field to sort the assets from the page.
        /// </summary>
        [DataMember(Name = "sortingField", IsRequired = true, EmitDefaultValue = true)]
        public string SortingField{ get; }
    }
}
