//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Unity.Cloud.Assets
{
    /// <summary>
    /// The pagination of the request.
    /// </summary>
    [DataContract(Name = "search_request_pagination")]
    internal class SearchRequestPagination
    {
        /// <summary>
        /// The pagination of the request.
        /// </summary>
        /// <param name="sortingField">The field with which to sort the assets.</param>
        /// <param name="sortingOrder">The order in which to sort the assets.</param>
        public SearchRequestPagination(string sortingField, string sortingOrder)
        {
            SortingField = sortingField;
            SortingOrder = sortingOrder;
        }

        /// <summary>
        /// The pagination token.
        /// </summary>
        [DataMember(Name = "token", EmitDefaultValue = false)]
        public string Token { get; set; }

        /// <summary>
        /// The amount of assets per page.
        /// </summary>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int Limit { get; set; }

        /// <summary>
        /// The field to sort the assets from the page.
        /// </summary>
        [DataMember(Name = "sortingField", IsRequired = true, EmitDefaultValue = true)]
        public string SortingField { get; }

        /// <summary>
        /// The order to sort the assets from the page.
        /// </summary>
        [DataMember(Name = "sortingOrder", IsRequired = true, EmitDefaultValue = true)]
        public string SortingOrder { get; }
    }
}
